---
- name: systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: restart docker
  service: "name=docker state={{ docker_restart_handler_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
